### ISSUE TITLE
Restarting kubernetes-ldap invalidates tokens

### ISSUE THREAD

**Issue by fungusakafungus** [proofpoint/kubernetes-ldap#14]
If read it correctly, kubernetes-ldap regenerates a keypair in current directory on every start.
Keypair is written even if these files already exist.

I've tried taking away write permission for the keypair files and then tokens survive server restart, even if this message is produced: `E0205 13:12:25.660391   95660 serve.go:184] Error generating key pair: open signing.priv: permission denied`

Another unexpected thing is that the keypair is written into current directory.

I think we should

1. make keypair path configurable (now the files are in current directory, named signing.priv and signing.pub)
2. provide a way to generate a keypair and exit (this would help my use case, I'd like to have multiple servers running kubernetes-ldap behind a load balancer, which all can validate the same token)
3. make kubernetes-ldap use the keypair if it is already there

**Comment by rajatjindal** [comment]
Hi, thank you very much for reporting the issue

Its a known issue and we do plan to fix it soon as we are working on hardening our deployments

I will really appreciate if you open a PR for this issue or stay tuned for the fix

**Comment by fungusakafungus** [comment]
By the way, I've noticed that persisting public key is not neccessary, it is derived from private key at https://github.com/proofpoint/kubernetes-ldap/blob/master/token/token.go#L66

**Comment by rajatjindal** [comment]
this has been implemented, so closing
